### PR TITLE
feat: Custom version format for source="scm"

### LINKED ISSUE #208: [Feature Request]How can we custom the format of the dynamic version generated by pdm when we use scm?
It's a common case to build and publish the package to PyPI at tagged commits and to TestPyPI on untagged commits. However, both PyPI and TestPyPI does not accept version string with a local version suffix. Therefore, it will be helpful to add a 'dev' suffix only when we are not exactly on a tag and use the local version '+dxxx' or '+gxxx' only when there is uncommited changes. So, how can we customize the formattion of the version string generated by pdm? If it's not supported now, can we support it in the future?

### PR DESCRIPTION
**Pull request by frostming**
Fixes #208

Signed-off-by: Frost Ming <me@frostming.com>

### CODE REVIEW

**Comment by whitequark** [comment]
@frostming Is it possible somehow to put the `format_version` function into `pdm_build.py` file where I have a `pdm_build_initialize` hook already? I don't want to add another file to my main package.

**Comment by whitequark** [comment]
@frostming Is it possible somehow to put the `format_version` function into `pdm_build.py` file where I have a `pdm_build_initialize` hook already? I don't want to add another file to my main package.

**Comment by frostming** [comment]
@whitequark you can put it in any file you like, why not.

**Comment by whitequark** [comment]
@frostming Thanks, I verified that this works for my use case. May I have a release of `pdm-backend`? I'm currently using a `git+https://` URL for `build-system.requires` but I think this may be poor practice...

**Comment by whitequark** [comment]
@frostming Friendly ping after a week--if you don't want or can't do a release for any reason I think I can reasonably use a git dependency to free you of responsibility, but it would really help to know what your plan is.

**Pull request merged**
